export const SET_CURRENT_BOOK = "SET_CURRENT_BOOK"
export const UPDATE_BOOKS = "UPDATE_BOOKS"
export const NEW_QUERY = "NEW_QUERY"
export const CLEAR_SEARCHES = "CLEAR_SEARCHES"
export const ADD_BOOK = "ADD_BOOK"
export const REMOVE_BOOK = "REMOVE_BOOK"