export const REMOVE_BOOK = "REMOVE_BOOK";
export const SAVE_BOOK = "SAVE_BOOK";
export const UPDATE_SAVED_BOOKS = "UPDATE_SAVED_BOOKS";
export const UPDATE_CURRENT_BOOK = "UPDATE_CURRENT_BOOK";
export const UPDATE_SEARCH_RESULTS = "UPDATE_SEARCH_RESULTS"